<template>
  <div>
    <Stage title="Jede Frage ist ein <br/> Schritt richtung Hilfe" image="image4" />
    <h1>FAQ</h1>
    <FaqItem :content="faq" />
  </div>
</template>

<script setup>
const faq = [
  { question: "Wie arbeitet der Verein?", answer: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum consequuntur officia, sequi perferendis repudiandae odio eos fugit cum animi corrupti corporis autem maxime aliquid beatae eius possimus impedit id necessitatibus sapiente explicabo voluptates cumque dolorem dolore. Delectus eius culpa accusantium voluptatum pariatur dicta voluptatem recusandae est! Inventore amet unde expedita eaque commodi culpa deserunt quidem soluta mollitia magnam voluptas iusto aperiam, blanditiis quasi odio atque adipisci. Nisi fugiat nam vero nostrum, ab inventore, magni provident aspernatur quae obcaecati praesentium itaque odio totam officiis quo asperiores. Adipisci labore dolorum nemo vero voluptatibus omnis nam maiores unde amet obcaecati quisquam facilis, cum fuga voluptatum cupiditate vitae a sequi similique iusto illum perspiciatis explicabo repellendus. Corrupti natus eaque sequi tenetur, labore esse repellat est optio maxime error quidem ipsam saepe perferendis voluptatem corporis. Quo unde delectus hic architecto magni ab quasi ex doloremque, a impedit dignissimos provident mollitia rerum aperiam porro? Commodi error, ut animi dolorem nostrum molestias soluta quos repellat harum voluptate eveniet iste distinctio velit cupiditate magni obcaecati ullam ex a vel laudantium praesentium hic ipsa. Cumque magni sunt cupiditate nobis illum odio repudiandae ipsam incidunt quisquam, facilis asperiores et voluptatibus nihil minus quae voluptates optio accusamus, doloribus quia id. Ipsam." },
  { question: "Wer wird durch den Verein Unerstützt?", answer: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum consequuntur officia, sequi perferendis repudiandae odio eos fugit cum animi corrupti corporis autem maxime aliquid beatae eius possimus impedit id necessitatibus sapiente explicabo voluptates cumque dolorem dolore. Delectus eius culpa accusantium voluptatum pariatur dicta voluptatem recusandae est! Inventore amet unde expedita eaque commodi culpa deserunt quidem soluta mollitia magnam voluptas iusto aperiam, blanditiis quasi odio atque adipisci. Nisi fugiat nam vero nostrum, ab inventore, magni provident aspernatur quae obcaecati praesentium itaque odio totam officiis quo asperiores. Adipisci labore dolorum nemo vero voluptatibus omnis nam maiores unde amet obcaecati quisquam facilis, cum fuga voluptatum cupiditate vitae a sequi similique iusto illum perspiciatis explicabo repellendus. Corrupti natus eaque sequi tenetur, labore esse repellat est optio maxime error quidem ipsam saepe perferendis voluptatem corporis. Quo unde delectus hic architecto magni ab quasi ex doloremque, a impedit dignissimos provident mollitia rerum aperiam porro? Commodi error, ut animi dolorem nostrum molestias soluta quos repellat harum voluptate eveniet iste distinctio velit cupiditate magni obcaecati ullam ex a vel laudantium praesentium hic ipsa. Cumque magni sunt cupiditate nobis illum odio repudiandae ipsam incidunt quisquam, facilis asperiores et voluptatibus nihil minus quae voluptates optio accusamus, doloribus quia id. Ipsam." },
  { question: "Wie wird meine Spende verwendet?", answer: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum consequuntur officia, sequi perferendis repudiandae odio eos fugit cum animi corrupti corporis autem maxime aliquid beatae eius possimus impedit id necessitatibus sapiente explicabo voluptates cumque dolorem dolore. Delectus eius culpa accusantium voluptatum pariatur dicta voluptatem recusandae est! Inventore amet unde expedita eaque commodi culpa deserunt quidem soluta mollitia magnam voluptas iusto aperiam, blanditiis quasi odio atque adipisci. Nisi fugiat nam vero nostrum, ab inventore, magni provident aspernatur quae obcaecati praesentium itaque odio totam officiis quo asperiores. Adipisci labore dolorum nemo vero voluptatibus omnis nam maiores unde amet obcaecati quisquam facilis, cum fuga voluptatum cupiditate vitae a sequi similique iusto illum perspiciatis explicabo repellendus. Corrupti natus eaque sequi tenetur, labore esse repellat est optio maxime error quidem ipsam saepe perferendis voluptatem corporis. Quo unde delectus hic architecto magni ab quasi ex doloremque, a impedit dignissimos provident mollitia rerum aperiam porro? Commodi error, ut animi dolorem nostrum molestias soluta quos repellat harum voluptate eveniet iste distinctio velit cupiditate magni obcaecati ullam ex a vel laudantium praesentium hic ipsa. Cumque magni sunt cupiditate nobis illum odio repudiandae ipsam incidunt quisquam, facilis asperiores et voluptatibus nihil minus quae voluptates optio accusamus, doloribus quia id. Ipsam." },
  { question: "Kann ich meine Spende von der Steuer absetzen?", answer: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum consequuntur officia, sequi perferendis repudiandae odio eos fugit cum animi corrupti corporis autem maxime aliquid beatae eius possimus impedit id necessitatibus sapiente explicabo voluptates cumque dolorem dolore. Delectus eius culpa accusantium voluptatum pariatur dicta voluptatem recusandae est! Inventore amet unde expedita eaque commodi culpa deserunt quidem soluta mollitia magnam voluptas iusto aperiam, blanditiis quasi odio atque adipisci. Nisi fugiat nam vero nostrum, ab inventore, magni provident aspernatur quae obcaecati praesentium itaque odio totam officiis quo asperiores. Adipisci labore dolorum nemo vero voluptatibus omnis nam maiores unde amet obcaecati quisquam facilis, cum fuga voluptatum cupiditate vitae a sequi similique iusto illum perspiciatis explicabo repellendus. Corrupti natus eaque sequi tenetur, labore esse repellat est optio maxime error quidem ipsam saepe perferendis voluptatem corporis. Quo unde delectus hic architecto magni ab quasi ex doloremque, a impedit dignissimos provident mollitia rerum aperiam porro? Commodi error, ut animi dolorem nostrum molestias soluta quos repellat harum voluptate eveniet iste distinctio velit cupiditate magni obcaecati ullam ex a vel laudantium praesentium hic ipsa. Cumque magni sunt cupiditate nobis illum odio repudiandae ipsam incidunt quisquam, facilis asperiores et voluptatibus nihil minus quae voluptates optio accusamus, doloribus quia id. Ipsam." },
]
</script>